load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "hello",
    srcs = ["hello.go"],
    importpath = "github.com/josiahsrc/bazel_playground/01_bazel_gazelle/pkg/hello",
    visibility = ["//visibility:public"],
)
