load("@bazel_gazelle//:def.bzl", "gazelle")

# gazelle:prefix github.com/josiahsrc/bazel_playground/01_bazel_gazelle
gazelle(
    name = "gazelle",
    extra_args = [
        "--build_file_name",
        "BUILD,BUILD.bazel",
    ],
)
