load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "another",
    srcs = ["another_pkg.go"],
    importpath = "github.com/josiahsrc/bazel_playground/00_golang_hello/another",
    visibility = ["//visibility:public"],
)
