load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "something",
    srcs = ["something.go"],
    importpath = "github.com/josiahsrc/bazel_playground/02_bazel_protobufs/go/internal/something",
    visibility = ["//02_bazel_protobufs/go:__subpackages__"],
)
