load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "something",
    srcs = [
        "another.go",
        "something.go",
    ],
    importpath = "github.com/josiahsrc/bazel_playground/01_bazel_gazelle/pkg/something",
    visibility = ["//visibility:public"],
)
