load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "internal",
    srcs = ["something.go"],
    importpath = "github.com/josiahsrc/bazel_playground/01_bazel_gazelle/internal",
    visibility = ["//:__subpackages__"],
)
